
apiVersion: v1
kind: Service
metadata:
  name: crud-nodejs
  namespace: student-api
spec:
  selector:
    app: crud-nodejs
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-nodejs
  namespace: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-nodejs
  template:
    metadata:
      labels:
        app: crud-nodejs
    spec:
      nodeSelector:
        type: application
      containers:
        - name: crud-nodejs
          imagePullPolicy: Always
          image: tejasdurge55/mongo-crud-one2n-sre-bootcamp
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
